services:
  db:
    image: bdd_projet
    expose:
      - "3306"
    networks:
      - backend

  api:
    image: projet_dp_api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bdd_projet_dp
    ports:
      - "8082:8082"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"